apiVersion: apps/v1
kind: Deployment
metadata:
  name: conduit-frontend
spec:
  replicas: 2
  minReadySeconds: 15
  selector:
    matchLabels:
      app: conduit-frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: conduit-frontend
    spec:
      containers:
        - image: localhost:5000/com.conduitapp/frontend
          imagePullPolicy: Always
          name: conduit-frontend
          ports:
            - containerPort: 80