apiVersion: v1
kind: Pod
metadata:
  name: conduit-frontend
  labels:
    app: frontend
spec:
  containers:
    - image: localhost:5000/com.conduitapp/frontend
      imagePullPolicy: Never
      name: conduit-frontend
      ports:
        - containerPort: 80