apiVersion: apps/v1
kind: Deployment
metadata:
  name: conduit-api
spec:
  replicas: 2
  minReadySeconds: 15
  selector:
    matchLabels:
      app: conduit-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: conduit-api
    spec:
      containers:
        - image: localhost:5000/com.conduitapp/api
          imagePullPolicy: Always
          name: conduit-api
          ports:
            - containerPort: 8080